In [5]:
#logging 
import logging
logging.basicConfig(filename="25FebInfo.log", level=logging.INFO, format="%(asctime)s %(name)s %(message)s")
logging.info("Pandas Working Started ") 

In [6]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , "5" ]
array_list = np.array(object = list_)


type(list_)
type(array_list)

numpy.ndarray

In [7]:
# Answer1
"""
There is difference in datatype of list_ and array_list . 
1 list_ is a list data type .
2 while array_list is a numpy.ndarray
"""

# Now See the code 
logging.info(" types is Explaning below with code")
print(type(list_))
print(type(array_list))



<class 'list'>
<class 'numpy.ndarray'>


In [8]:
# Answer2

# The data type of the each and every element of list and arra_list
# 1
logging.info("Type of each elemtn of the list_ variable")
#code
for element in list_:  
     print(type(element))

# exaplantion
"""
the type of element of list_ variable is string 'str' 
"""

# 2
logging.info("Type of each elemtn of the array_list variable")

# code
for element in array_list:
     print(type(element))


# explantion
"""
The type of the element of the array_list is numpy.str 
the type of the list_ is str.
"""


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


'\nThe type of the element of the array_list is numpy.str \nthe type of the list_ is str.\n'

In [9]:
# ANswer3

import numpy as np
list_ = [ '1' , '2' , '3' , '4' , "5" ]

array_list = np.array(object = list_, dtype = int)
logging.info("Data Type of each element is in list_ is ")

#for list_ 
for element in list_:
    print(type(element))

    
# For array_list
for element in array_list:
    print(type(element))



# Explnation
"""
yes There is difference in data tyype of list_ and array_list is.
list_ dtype is str. while array_list is casted to int .
"""


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


'\nyes There is difference in data tyype of list_ and array_list is.\nlist_ dtype is str. while array_list is casted to int .\n'

In [10]:
# Q4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Answer4
# 1 shape

shap =num_array.shape
print("The shape of the above array is :", shap)

# 2 size
siz = num_array.size
print("The size of the above array is :", siz)


The shape of the above array is : (2, 3)
The size of the above array is : 6


In [21]:
# Answer5
"""
Creating  numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
"""
logging.info("creating the 3*3 matrix with zeroes element ")
logging.info("using the np.zeros to generate the matrix")
import numpy as np
arr = np.zeros((3,3))
print(arr)
#size of the matriz is :
print("\nThe size of the zeros matriz is :",arr.size)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

The size of the zeros matriz is : 9


In [25]:
# Answer6
# Identity matrix of shape (5,5) using numpy functions

logging.info("using the numpy package to create the idenetiy matrix ")
import  numpy as np
logging.info("using the numpy.eye() to create the identity matrix")
identity_matrix = np.eye( N= 5,M=5 )
# print 
identity_matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])